name: CuriosPaper
version: '${project.version}'
main: org.bg52.curiospaper.CuriosPaper
api-version: '1.14'
author: Brothergaming52
description: Custom accessory inventory system API for Paper

commands:
  curios:
    description: CuriosPaper admin and debug commands
    usage: /curios <rp|debug>
    permission: curiospaper.admin
    aliases: [cp, curiospaper]
  baubles:
    description: Open the accessory inventory
    aliases: [b, bbag]
    usage: /<command>
  edit:
    description: Create and edit custom items
    usage: /edit <create|gui|delete|list> [itemname]
    permission: curiospaper.edit
    aliases: [itemedit]

permissions:
  curiospaper.admin:
    description: Access to admin commands
    default: op
  curiospaper.edit:
    description: Create and edit custom items
    default: op
